### ISSUE TITLE
Translator bot does not work in forms or threads

### ISSUE THREAD

**Issue by Rainmangames** [ffouqueray/Translator-Bot#3]
hello! i have noticed the bot will not read in forms or threads, even if it is a administrator for the server.

**Comment by UnBonWhisky** [comment]
Hello,

That is because the bot is using a deprecated version of discord api. So it actually does not work on these channel types :  
- text channel in voice channel
- threads
- forums channels

It is asking a full rewrite to update the bot to the last version of discord API, and to add these channels to the bot.  
When I have time for that, I will update the code to make it work again with the new discord functionalities.

**Comment by UnBonWhisky** [comment]
Hello @Rainmangames 
I have updated the bot, now it can handle all the types I have said.
These settings will inherit from the base channel.
Threads will have same channel language setup than the parent channel language.
