### ISSUE TITLE
[Feature request] non-clutter in-channel translations

### ISSUE THREAD

**Issue by Dima793** [ffouqueray/Translator-Bot#7]
The bot is nice overall, but it doesn't seem to be a good pick for announcement channels because in-channel translations will clutter those channels for everyone and DM translations might not be convenient enough to server members.

Could you please consider making an option for flag react translations to only be shown to the user who added the flag reaction, not to everyone? Similar to how /help message is.

If that's not technically possible could you please consider making an option for the bot to dump all flag react translations into a single channel? Making a separate channel for each supported language would only clutter the server on top of adding a lot of unnecessary work for mods to set it up if they don't want to limit the translations to a predetermined selection of only a few languages.

However, that should only cover flag react translations. I like how /defaultlanguage can do automatic one-way in-channel translatuons for everything_except_english -> english, but I'd like to set other translations (one-way english -> any_other_language) that are used by particular users individually to not clutter the server for everyone, without having to make those users switch between the server and DMs for every message.

**Comment by UnBonWhisky** [comment]
Hello !

The feature you are requesting is not possible because of Discord limitations. The ephemeral messages (the ones that only you can see) are available only for slash commands.

However, I have recently added (between the 20th and the 25th august) the Context App Commands.

When you right click on a message, you have got the "Apps" menu. Hover over it, you will get some translation commands you can use. It will make the same as flag reaction but only visible for you.

The "Translate" option uses the discord client language, but can be bypassed if your language does not exists as discord client using the `/personal` command.

If you have any question reguarding this, do not hesitate to respond to this message.

All my bests,
UnBonWhisky

EDIT : For mobiles, you have to long press on a message to get the "Apps" context menu. These features are user installable to work in DM, in servers the bot is not in, and in the servers the bot is in.
