### ISSUE TITLE
[feature-request] Translating embed posts from other bots 

### ISSUE THREAD

**Issue by flopacaud** [ffouqueray/Translator-Bot#9]
Hi ,

Thanks so much for your work !

The bot does an amazing job for all the required basic translations and is very useful for small server that cannot invest in paying a lot for a translation bot. Something it does not seem to do, however, is to read in the embed messages of other bots and translate them (even with flag reaction).
Personal example: NASABot (https://top.gg/bot/748775876077813881) which returns a embed message to display their astronomy picture of the day together with some explanations (command /apod).
Most translation tools (even the ones with a premium plan) seem to not include this feature. I believe it is for security reasons since the behaviour of the other bots may trigger uncontrolled reactions.

I have seen one bot that allows it though, with a simple security solution.
It is the bot Translator by New View (https://top.gg/bot/360081866461806595) which simply requires the admin to create a 'can-translate' role and  adds to a whitelist for the server each bot which has been assigned this role (see their doc here: https://nvu.io/en/bots/discord-translator/wiki/translate-bots-and-webhooks/). Only this/these bots will then be translated.

Would you consider implementing a similar solution to allow individual trusted bots ?

**Comment by UnBonWhisky** [comment]
Hello !
This is one of the feature request in the discord support server.
Actually, it is in my plans for the future of the bot, but I can not provide ETA because developent and testing are not an easy task due to how the embeds are done (I have to dynamically make them again), and how the /linkchannels configuration is done today.
I can not provide ETA but don't wordy, I keep in mind to build this feature.
